### ISSUE TITLE
cadc-storage-adapter-fs: MacOS does not support Files.getFileAttributeView()

### ISSUE THREAD

**Issue by at88mph** [opencadc/storage-inventory#229] opened 2020-11-06 18:30 UTC
MacOS file system does not support the Java `Files.getFileAttributeView()`.

See OpenJDK bug:
https://bugs.openjdk.java.net/browse/JDK-8030048

**Comment by pdowler** [comment] 2020-11-09 19:56
duplicate of #111

**Closed by pdowler** 2020-11-09 19:56 UTC
